services:
  findergen:
    build:
      context: .
      dockerfile: docker/findergen/Dockerfile
    container_name: findergen
    ports:
      - "3013:3013"

  template-site:
    build:
      context: .
      dockerfile: docker/template-site/Dockerfile
    container_name: template-site
    ports:
      - "3014:3014"
    depends_on:
      - findergen

  static-site:
    build:
      context: .
      dockerfile: docker/static-site/Dockerfile
    container_name: static-site
    ports:
      - "3016:3016"

  uploadpage:
    build:
      context: ./npm/hub
      dockerfile: ../../docker/uploadpage/Dockerfile
    container_name: uploadpage
    ports:
      - "3015:3015"