// Auto-generated by vite-plugin-pages-ssg. Do not edit by hand.

declare module "virtual:pages" {
  export interface PageModule {
    /** Called with the mount element on the client. */
    default: (el: HTMLElement) => void | Promise<void>;
    [key: string]: unknown;
  }

  export interface ComponentPage {
    id: string;
    type: "component";
    load: () => Promise<PageModule>;
    styles: string[];
  }

  export interface MarkdownPage {
    id: string;
    type: "markdown";
    markdown?: string;
    html: string;
    styles: string[];
  }

  export type PageEntry = ComponentPage | MarkdownPage;

  export const pages: Record<string, PageEntry>;
}
