/*
 * decode base64
 */
function d(inp) {
  return decodeURIComponent(escape(inp));

  return decodeURIComponent(escape(atob(inp)));
}

/*
 * encode base64
 */
function e(inp) {
  return unescape(encodeURIComponent(inp));

  return btoa(unescape(encodeURIComponent(inp)));
}

/*
 * function to parse the buildmacros
 */
function parseBuildMacros(bm) {
  let out = "#ifdef SAMFILE_BUILD\n";

  const lines = bm.split(/\r?\n/);
  for (const line of lines) {
    out += "\t";
    out += line;
  }

  out += "\n#endif";

  return out;
}

/*
 * group the know sections together
 */
function groupSections(fling, settings, types) {
  let sec = {
    fling: e(fling),
    settings: e(settings),
    types: e(types),
  };

  return sec;
}

/*
 * make json object
 */
export function genSamfileJson(
  version,
  flingsec,
  ssec,
  stypes,
  sections,
  macros,
  samfile,
  batch2,
  buildmacros,
  lua,
  js,
) {
  let obj = {};
  obj.version = version;
  obj.customsections = e(sections);
  obj.macros = e(macros);
  obj.buildmacros = e(buildmacros);
  obj.sections = {
    fling: e(flingsec),
    settings: e(ssec),
    types: e(stypes),
    samfile: e(samfile),
    batch2: e(batch2),
    js: e(js),
    lua: e(lua),
  };

  return obj;
}

/*
 * generate a samfile source
 */
export function genSamfile(obj) {
  if (obj.version == "") {
    obj.version = "2";
  }

  let value = `// autogenerated samfile   
      
#define VERSION ${obj.version}     

${d(obj.macros)}  
    
%%section FLING
${d(obj.sections.fling)}
%%endsection
    
%%section SETTINGS
${d(obj.sections.settings)}
%%endsection
    
%%section SAMFILE
${d(obj.sections.samfile)}
%%endsection
    
%%section BATCH
${d(obj.sections.batch2)}
%%endsection
    
%%section TYPES
${d(obj.sections.types)}
%%endsection
    
%%section JS
${d(obj.sections.js)}
%%endsection
    
    
%%section LUA
${d(obj.sections.lua)}
%%endsection    
    
${d(obj.customsections)}
    
${parseBuildMacros(d(obj.buildmacros))}
      
%%section SAMFILEGENERATOR_DATA
${JSON.stringify(obj)}
%%endsection 
`;

  return value;
}

/*
 * converts the SAMFILEGENERATOR_DATA back into import data
 * for the generator
 */
export function restoreSamfile(content) {
  const lines = content.split(/\r?\n/);
  let datalines = "";
  let addsec = false;

  for (const line of lines) {
    if (line.startsWith("%%section SAMFILEGENERATOR_DATA")) {
      addsec = true;
      continue;
    }
    if (line.startsWith("%%endsection")) {
      addsec = false;
      continue;
    }
    if (addsec) {
      datalines += line;
    }
  }

  return JSON.parse(datalines);
}
